Milestone-4
AkintoyeOlamide/Calculator pull request #6
Opened 2021-07-14 09:04 UTC by AkintoyeOlamide

Adding the logic for the calculator

2021-07-14 12:42 UTC, Elbie-em requested changes
## STATUS: CHANGES REQUIRED 🟡  ♻️ 

Hi @AkintoyeOlamide, you have done a great job so far. I like how you are wrapping your operations in a try-catch block. However, there are some minor changes needed before moving forward. Check my comments below for more details ⬇️ 

*All the best and keep up the good work* 💪 

#### *After applying the requested changes, you can submit another code review request*

> Elbie Moonga (Part-time TSE)

> Github (@Elbie-em)
> Slack (Elbie Moonga)
> Twitter ([@ElbieEm](https://twitter.com/ElbieEm))
> LinkedIn([Elbie Moonga](https://www.linkedin.com/in/elbiemoonga/))

2021-07-14 12:42 UTC, Elbie-em commented on src/logic/operate.js
> +    }
- [ ] You are creating a new instance BIg in every case after you  have wrapped numberOne and numberTwo. You can simply find the result by e.g
```
if (operation === '+') {
      result = num1.plus(num2);
 }
```

2021-07-14 12:42 UTC, Elbie-em commented on src/logic/operate.js
> +      result = Big(num1.div(100));
- [ ] You should use the modifier function for this case here as required.

2021-07-16 03:10 UTC, uche-inyama approved these changes
## Approved

### Hi Olamide :slightly_smiling_face: 

Go ahead with the next milestone.

### Happy coding :man_technologist: 

#### ``` Uchechukwu Henry Inyama ```

2021-07-16 03:10 UTC, uche-inyama commented on src/logic/operate.js
> +
Why did you prefix the '+' sign in **numberOne & numberTwo**

2021-07-16 07:36 UTC, merged